name: flutter_web_signin
description: A new Flutter project.

version: 1.0.0+1

dependencies:
  flutter_web:
  flutter_web_ui:

dev_dependencies:
  flutter_web_test:
  build_runner:
  build_web_compilers:
  test:

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test

