name: flutter_web_signin
description: A new Flutter project.

version: 1.0.0+1

dependencies:
  flutter_web: any
  flutter_web_ui: any

dev_dependencies:
  flutter_web_test: any
  build_runner: any
  build_web_compilers: any
  test: any

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test

